### ISSUE TITLE
How is it possible to set the node count?

### ISSUE THREAD

**Issue by tomberget** [evry-ace/tf-azure-aks#29]
I am trying to make the MBAS Infrastructure work (just run terraform plan), and there is one item in that script that no longer seems to exist in this module: `agent_count` is no longer there.

It seems like there is a replacement for agent_count, which I believe is node_count. However, there is no variable with that name, and it also does not seem possible to overwrite the node_count value in any way.

For MBAS, they current have three nodes running for the G2 application. If I omit agent_count/node_count, I would be left with only 2.

Am I missing, or misinterpreting something?

**Comment by bjorges** [comment]
Like this
module "aks" {
  source                  = "github.com/evry-ace/tf-azure-aks?ref=v0.14.2"
...
  default_pool = {
    node_count = var.aks_node_count
  }
}
